import assert from 'node:assert/strict';
import { chromium } from 'playwright';
const browser=await chromium.launch({headless:true,channel:'chrome'});
try {
 const target=process.env.TEST_URL || 'http://127.0.0.1:4190';
 const page=await browser.newPage({reducedMotion:'reduce'});
 await page.route('https://**/*',route=>new URL(route.request().url()).host===new URL(target).host?route.continue():route.abort());
 await page.goto(target,{waitUntil:'domcontentloaded'});
 await page.getByRole('button',{name:'New blank plan',exact:true}).click();
 const guide=page.getByRole('region',{name:'Finish your cash inputs'});
 assert.match(await guide.innerText(),/41 amounts need/);
 const next=page.getByRole('button',{name:'Go to next amount'});
 await next.click();
 assert.equal(await page.locator(':focus').getAttribute('id'),'cash-opening');
 await page.getByLabel('Cash available today ($)',{exact:true}).fill('50000');
 await next.click();
 assert.equal(await page.locator(':focus').getAttribute('id'),'cash-reserve');
 await page.getByLabel('Minimum cash reserve ($)',{exact:true}).fill('10000');
 await next.click();
 assert.equal(await page.locator(':focus').getAttribute('id'),'cash-week-1-receipts');
 await page.getByText('Paste 13 weeks from a spreadsheet',{exact:true}).click();
 await page.getByLabel('Weekly rows',{exact:true}).fill(Array.from({length:13},()=> '1000\t500\t0').join('\n'));
 await page.getByRole('button',{name:'Apply weekly rows',exact:true}).click();
 assert.equal(await guide.count(),0,'Complete cash plans have no completion prompt');
 await page.getByLabel('Week 8 costs',{exact:true}).fill('');
 assert.match(await guide.innerText(),/1 amount needs/);
 assert.match(await guide.innerText(),/Weekly amounts: week 8\./);
 await next.click();
 assert.equal(await page.locator(':focus').getAttribute('id'),'cash-week-8-costs');
 await page.getByLabel('Week 8 costs',{exact:true}).fill('-1');
 assert.match(await guide.innerText(),/1 amount needs/,'Invalid values also need attention');
 await page.getByLabel('Week 8 costs',{exact:true}).fill('0');
 assert.equal(await guide.count(),0,'Zero is a valid explicit amount');
 assert.equal(await page.getByLabel('Week 8 receipts',{exact:true}).inputValue(),'1000','Guidance never changes other inputs');
 await page.getByLabel('Week 9 other outflows',{exact:true}).fill('');
 await page.setViewportSize({width:390,height:844});
 await next.click();
 assert.equal(await page.locator(':focus').getAttribute('id'),'cash-week-9-overhead');
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'Mobile page has no horizontal overflow');
 console.log('PASS: blank-plan guidance, focused next input, paste completion, invalid/zero values, untouched amounts and mobile focus.');
} finally {await browser.close();}
