import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import { createPlan } from '../../src/cash-workspace/model.js';
const browser=await chromium.launch({headless:true,channel:'chrome'});
try {
 const page=await browser.newPage();
 const target=process.env.TEST_URL || 'http://127.0.0.1:4190';
 await page.route('https://**/*', route=>new URL(route.request().url()).host===new URL(target).host?route.continue():route.abort());
 await page.goto(target,{waitUntil:'domcontentloaded'});
 await page.waitForLoadState('networkidle');
 const cash=page.getByRole('spinbutton',{name:'Cash available today ($)',exact:true});
 let dialogs=0;let accept=false;
 page.on('dialog',async dialog=>{dialogs++;assert.equal(dialog.type(),'confirm');await (accept?dialog.accept():dialog.dismiss());});
 await page.getByRole('button',{name:'New blank plan',exact:true}).click();
 assert.equal(dialogs,0,'Untouched example needs no replacement warning');
 assert.equal(await cash.inputValue(),'');
 await page.reload();await page.waitForLoadState('networkidle');
 await cash.fill('101000');
 await page.getByRole('button',{name:'New blank plan',exact:true}).click();
 assert.equal(dialogs,1);assert.equal(await cash.inputValue(),'101000','Cancel retains edited example');
 assert.match(await page.locator('.cw-badge').innerText(),/EXAMPLE DATA/,'Edits do not fabricate own-data activation');
 await page.getByRole('button',{name:'Load example',exact:true}).click();
 assert.equal(dialogs,2);assert.equal(await cash.inputValue(),'101000');
 accept=true;await page.getByRole('button',{name:'Load example',exact:true}).click();
 assert.equal(dialogs,3);assert.equal(await cash.inputValue(),'95000');
 await cash.fill('102000');await page.getByRole('button',{name:'Save on browser',exact:true}).click();
 await page.reload();await page.waitForLoadState('networkidle');
 accept=false;await page.getByRole('button',{name:'New blank plan',exact:true}).click();
 assert.equal(dialogs,4);assert.equal(await cash.inputValue(),'102000','Saved example is protected after reload');
 const file={name:'example.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(createPlan(true)))};
 await page.locator('input[type="file"]').setInputFiles(file);
 await page.waitForFunction(()=>document.querySelector('input[type="file"]').value==='');
 assert.equal(dialogs,5);assert.equal(await cash.inputValue(),'102000','Canceled import retains saved plan');
 accept=true;await page.locator('input[type="file"]').setInputFiles(file);
 await page.waitForFunction(()=>document.querySelector('input[type="file"]').value==='');
 assert.equal(dialogs,6);assert.equal(await cash.inputValue(),'95000');
 accept=false;await page.getByRole('button',{name:'New blank plan',exact:true}).click();
 assert.equal(dialogs,7);assert.equal(await cash.inputValue(),'95000','Imported example is protected');
 console.log('PASS: pristine example, cancel/accept replacement, saved reload, import cancellation and example labeling.');
} finally {await browser.close();}
