import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {chromium} from 'playwright';
const browser=await chromium.launch({headless:true,channel:'chrome'});
try {
 const page=await browser.newPage();const target=process.env.TEST_URL||'http://127.0.0.1:4191';
 await page.route('https://**/*',r=>new URL(r.request().url()).host===new URL(target).host?r.continue():r.abort());
 await page.goto(target,{waitUntil:'domcontentloaded'});
 await page.getByRole('tab',{name:/WIP check/}).click();
 await page.getByText('Paste jobs from a spreadsheet',{exact:true}).click();
 const input=page.getByRole('textbox',{name:'Job rows'});
 await input.fill('School\t400000\t180000.25\t320000\t200000.50\nFit-out\t250000\t130000\t265000\t145000');
 await page.getByRole('button',{name:'Check pasted jobs',exact:true}).click();
 assert.equal(await page.getByRole('textbox',{name:'Job name',exact:true}).first().inputValue(),'Riverside school','Preview leaves plan intact');
 let accept=false;page.on('dialog',d=>accept?d.accept():d.dismiss());
 await page.getByRole('button',{name:'Replace WIP jobs',exact:true}).click();
 assert.equal(await page.getByRole('textbox',{name:'Job name',exact:true}).first().inputValue(),'Riverside school');
 accept=true;await page.getByRole('button',{name:'Replace WIP jobs',exact:true}).click();
 assert.equal(await page.getByRole('textbox',{name:'Job name',exact:true}).first().inputValue(),'School');
 await page.getByRole('spinbutton',{name:'Report cost-to-date total ($)',exact:true}).fill('310000.25');
 await page.getByRole('spinbutton',{name:'Report billed-to-date total ($)',exact:true}).fill('345000.50');
 await page.getByRole('textbox',{name:'Report name and cut-off date',exact:true}).fill('Job ledger · August 31, 2026');
 await page.getByRole('heading',{name:'Both entered totals match'}).first().waitFor({state:'visible'});
 await page.getByRole('spinbutton',{name:'Report cost-to-date total ($)',exact:true}).fill('310000.24');
 assert.match(await page.locator('.cw-wip-tools').innerText(),/Cost difference: \$0.01/);
 await input.fill('Bad\t1\t2\t1\t0');await page.getByRole('button',{name:'Check pasted jobs',exact:true}).click();
 assert.match(await page.getByRole('alert').innerText(),/current jobs have not changed/);
 assert.equal(await page.getByRole('textbox',{name:'Job name',exact:true}).first().inputValue(),'School');
 const downloading=page.waitForEvent('download');await page.getByRole('button',{name:'Export WIP CSV',exact:true}).click();
 const download=await downloading;const csv=await readFile(await download.path(),'utf8');assert.match(csv,/180000.25/);assert.match(csv,/Review: estimated loss/);
 await page.getByRole('button',{name:'Save on browser',exact:true}).click();await page.reload({waitUntil:'domcontentloaded'});
 await page.getByRole('tab',{name:/WIP check/}).click();
 assert.equal(await page.getByRole('textbox',{name:'Report name and cut-off date',exact:true}).inputValue(),'Job ledger · August 31, 2026');
 assert.match(await page.locator('.cw-print').textContent(),/Cost difference: \$0.01/);
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'No mobile page overflow');
 await page.screenshot({path:'/Users/camre/Documents/Codex/2026-09-08/g/outputs/BondSBA-wip-mobile.png',fullPage:true});
 console.log('PASS: WIP preview/cancel/apply, cents reconciliation, invalid batch, CSV, saved controls, printed summary, mobile width.');
} finally {await browser.close();}
