// src/domains/sba-loans/components/FeeWaiverCalculator.jsx
// FY2026 SBA Manufacturer Fee Waiver Calculator.
// Target: NAICS 31–33 (Manufacturing) — waiver active through Sept 30, 2026.
// Shows upfront guaranty fee savings vs standard fee in real-time.
// "Download Term Sheet" is gated behind LeadCaptureModal.
import { useState } from 'react';
import { Download, Info } from 'lucide-react';
import { LeadCaptureModal } from '../../../components/LeadCaptureModal';

// ── FY2026 SBA 7(a) Guaranty Fee Schedule ─────────────────────────────────────
// Guaranteed portion: 85% flat for ALL loan sizes
// Standard fees (non-manufacturer) on guaranteed portion:
//   ≤$150k: 2.0%
//   $150k–$700k: 3.0%
//   >$700k: 3.5% flat
// Manufacturer waiver (NAICS 31–33): upfront guaranty fee = $0 on loans ≤$5M.

export function calcGuarantyFee(loanAmount) {
  const amt = parseFloat(loanAmount) || 0;
  const guaranteed = amt * 0.85;

  let fee = 0;
  if (amt <= 150_000) {
    fee = guaranteed * 0.02;
  } else if (amt <= 700_000) {
    fee = guaranteed * 0.03;
  } else {
    fee = guaranteed * 0.035;
  }

  // Manufacturer waiver: $0 for loans ≤$5M (eligibility check done by lender).
  const manufacturerFee = amt <= 5_000_000 ? 0 : fee;
  const savings = fee - manufacturerFee;

  return { guaranteed, standardFee: fee, manufacturerFee, savings };
}

const currencyFmt = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 });

function fmt(n) {
  return currencyFmt.format(n);
}

function Slider({ label, min, max, step, value, onChange, format }) {
  const sliderLabelId = `slider-${label.replace(/\s+/g, '-').toLowerCase()}`;
  return (
    <div>
      <div className="flex items-center justify-between mb-2">
        <label id={sliderLabelId} className="text-[12px] font-semibold uppercase tracking-wider text-slate-500">{label}</label>
        <span className="text-[15px] font-bold tabular-nums text-slate-900">{format(value)}</span>
      </div>
      <input
        type="range"
        min={min}
        max={max}
        step={step}
        value={value}
        onChange={(e) => onChange(Number(e.target.value))}
        aria-labelledby={sliderLabelId}
        className="w-full accent-[#0B1F3A]"
      />
      <div className="flex justify-between mt-1 text-[11px] text-slate-400">
        <span>{format(min)}</span>
        <span>{format(max)}</span>
      </div>
    </div>
  );
}

// Generates a printable term sheet via window.print() — no server needed.
function openPrintTermSheet({ loanAmount, interestRate, result, onError }) {
  const win = window.open('', '_blank');
  if (!win) {
    onError?.('Your browser blocked the print window. Please allow popups for this site.');
    return;
  }
  win.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>SBA 7(a) Fee Waiver — Executive Term Sheet</title>
      <style>
        body { font-family: Georgia, serif; max-width: 700px; margin: 40px auto; color: #0f172a; line-height: 1.6; }
        h1 { font-size: 22px; border-bottom: 2px solid #0B1F3A; padding-bottom: 8px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        td, th { padding: 10px 12px; text-align: left; border: 1px solid #e2e8f0; font-size: 14px; }
        th { background: #f8fafc; font-weight: 600; }
        .highlight { background: #f0fdf4; font-weight: bold; color: #166534; }
        .footer { margin-top: 30px; font-size: 11px; color: #94a3b8; }
      </style>
    </head>
    <body>
      <h1>SBA 7(a) Manufacturer Fee Waiver — Executive Term Sheet</h1>
      <p><strong>Program:</strong> SBA 7(a) Standard Loan · FY2026 Manufacturing Fee Waiver (NAICS 31–33)</p>
      <p><strong>Waiver Valid Through:</strong> September 30, 2026</p>
      <table>
        <tr><th>Parameter</th><th>Value</th></tr>
        <tr><td>Loan Amount</td><td>${fmt(loanAmount)}</td></tr>
        <tr><td>Estimated Interest Rate</td><td>${interestRate.toFixed(2)}%</td></tr>
        <tr><td>SBA Guaranteed Portion (85%)</td><td>${fmt(result.guaranteed)}</td></tr>
        <tr><td>Standard Upfront Guaranty Fee</td><td>${fmt(result.standardFee)}</td></tr>
        <tr><td class="highlight">Manufacturer Fee (Waived)</td><td class="highlight">$0</td></tr>
        <tr><td class="highlight">Your Upfront Savings</td><td class="highlight">${fmt(result.savings)}</td></tr>
      </table>
      <p class="footer">
        This estimate is based on FY2026 SBA fee schedules and is for informational purposes only.
        Actual fees are determined by the SBA lender. Consult a licensed SBA lender or broker before proceeding.
        Generated by ClearPath SBA Loan Tools · clearpathsbaloan.com
      </p>
    </body>
    </html>
  `);
  win.document.close();
  win.focus();
  win.print();
}

export function FeeWaiverCalculator({ nav }) {
  const [loanAmount, setLoanAmount] = useState(500_000);
  const [interestRate, setInterestRate] = useState(7.5);
  const [gateOpen, setGateOpen] = useState(false);
  const [captured, setCaptured] = useState(false);
  const [printError, setPrintError] = useState('');

  const result = calcGuarantyFee(loanAmount);

  const handleCapture = (lead) => {
    setGateOpen(false);
    setCaptured(true);
    setPrintError('');
    openPrintTermSheet({
      loanAmount,
      interestRate,
      result,
      onError: setPrintError
    });
  };

  return (
    <div className="mx-auto max-w-2xl px-4 py-10">
      {/* Header */}
      <div className="mb-2">
        <span className="inline-block rounded-full border border-green-300 bg-green-50 px-3 py-0.5 text-[11px] font-bold uppercase tracking-widest text-green-700">
          FY2026 Waiver Active · Through Sept 30, 2026
        </span>
      </div>
      <h1 className="mt-3 text-[28px] font-bold tracking-tight text-slate-900 md:text-[32px]">
        SBA Manufacturer Fee Waiver Calculator
      </h1>
      <p className="mt-2 max-w-[54ch] text-[15px] text-slate-600 leading-relaxed">
        NAICS codes 31–33 (Manufacturing) qualify for a full upfront guaranty fee waiver on SBA 7(a)
        loans up to $5M. See your exact savings in real time.
      </p>

      <div className="flex items-start gap-2 mt-4 rounded-lg border border-blue-200 bg-blue-50 px-4 py-3">
        <Info className="mt-0.5 h-4 w-4 shrink-0 text-blue-600" />
        <p className="text-[12px] text-blue-800">
          The upfront SBA guaranty fee — typically 3–3.75% of the guaranteed amount — is waived at closing
          for eligible manufacturers. This is cash saved on Day 1.
        </p>
      </div>

      {/* Sliders */}
      <div className="mt-8 space-y-6 rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
        <Slider
          label="Loan Amount"
          min={50_000}
          max={5_000_000}
          step={25_000}
          value={loanAmount}
          onChange={setLoanAmount}
          format={(v) => fmt(v)}
        />
        <div>
          <Slider
            label="Estimated Interest Rate"
            min={5.0}
            max={14.0}
            step={0.25}
            value={interestRate}
            onChange={setInterestRate}
            format={(v) => v.toFixed(2) + '%'}
          />
          <p className="text-xs text-slate-400 mt-1">Used in term sheet only — does not affect SBA guaranty fee</p>
        </div>
      </div>

      {/* Savings callout */}
      <div className="mt-6 grid grid-cols-3 gap-3">
        {[
          { label: 'Standard Fee', value: fmt(result.standardFee), muted: true },
          { label: 'Manufacturer Fee', value: '$0', green: true },
          { label: 'You Save', value: fmt(result.savings), bold: true },
        ].map(({ label, value, muted, green, bold }) => (
          <div
            key={label}
            className={`rounded-xl border p-4 text-center ${green ? 'border-green-200 bg-green-50' : 'border-slate-200 bg-slate-50'}`}
          >
            <p className={`text-[11px] font-semibold uppercase tracking-wider ${green ? 'text-green-600' : 'text-slate-400'}`}>
              {label}
            </p>
            <p
              className={`mt-1 text-[22px] font-bold tabular-nums ${
                green ? 'text-green-700' : bold ? 'text-[#0B1F3A]' : muted ? 'text-slate-400 line-through' : 'text-slate-900'
              }`}
            >
              {value}
            </p>
          </div>
        ))}
      </div>

      {/* CTA */}
      {printError && (
        <div className="mt-6 rounded-lg border border-red-200 bg-red-50 px-4 py-3">
          <p className="text-[12px] text-red-800">{printError}</p>
        </div>
      )}
      <button
        type="button"
        onClick={() => {
          setPrintError('');
          if (captured) {
            openPrintTermSheet({ loanAmount, interestRate, result, onError: setPrintError });
          } else {
            setGateOpen(true);
          }
        }}
        className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-[#0B1F3A] px-6 py-4 text-[14px] font-bold text-white shadow-md hover:bg-[#12365F]"
      >
        <Download className="h-5 w-5" />
        Download Executive Term Sheet PDF
      </button>
      <p className="mt-2 text-center text-[11px] text-slate-400">Free · No credit card required</p>

      {gateOpen && (
        <LeadCaptureModal
          title="Download Executive Term Sheet PDF"
          subtitle="Your personalized SBA fee waiver term sheet — formatted for lender submission."
          ctaLabel="Send Me the PDF"
          onCapture={handleCapture}
          onClose={() => setGateOpen(false)}
        />
      )}
    </div>
  );
}

export default FeeWaiverCalculator;
