import React, { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, ArrowRight, Download, ShieldCheck, Plus, Trash2, FileCheck2, ChevronDown, Check, BarChart3, FolderOpen, Save, Printer } from 'lucide-react';
import { CHECKLIST, createPlan, forecast, wip, money, validatePlan, isCashComplete, cashCsv, blankJob, parseWeeklyPaste } from './model.js';
import './workspace.css';
import './hightech.css';
import WipTools, {WipReconciliationSummary} from './WipTools.jsx';
const STORAGE='bondsba-cash-plan-v1';
function download(name,body,type='application/json') { const url=URL.createObjectURL(new Blob([body],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000); }
function NumberField({label,value,onChange,...props}) { return <label className="cw-field"><span>{label}</span><input type="number" min="0" max="1000000000000" step="any" inputMode="decimal" value={value} onChange={e=>onChange(e.target.value)} {...props}/></label>; }
function Chart({base,stress,opening,reserve}) {
 const values=[Number(opening),...base.rows.map(r=>r.balance),...stress.rows.map(r=>r.balance),Number(reserve),0];
 const low=Math.min(...values)-10000, high=Math.max(...values)+10000;
 const y=n=>180-(n-low)/(high-low)*150;
 const points=rows=>[Number(opening),...rows.map(r=>r.balance)].map((n,i)=>`${48+i*36},${y(n)}`).join(' ');
 return <div className="cw-chart"><div className="cw-chart-label"><span><i/> Expected</span><span><i className="stress"/> Stress scenario</span></div><svg viewBox="0 0 540 220" role="img" aria-label={`13-week cash forecast. Expected low ${money(base.min)}. Stressed low ${money(stress.min)}. Detailed values in the weekly table.`}>
 {[low,(high+low)/2,high].map((n,i)=><g key={i}><line x1="48" x2="520" y1={y(n)} y2={y(n)} stroke="#e5e9e7"/><text x="1" y={y(n)+4} fontSize="10" fill="#69766f">{Math.round(n/1000)}k</text></g>)}
 <line x1="48" x2="520" y1={y(Number(reserve))} y2={y(Number(reserve))} stroke="#87968e" strokeDasharray="3 5"/><polyline points={points(base.rows)} fill="none" stroke="#235a49" strokeWidth="3"/><polyline points={points(stress.rows)} fill="none" stroke="#c45d35" strokeWidth="3" strokeDasharray="7 4"/>
 {[0,4,8,13].map(i=><text key={i} x={48+i*36} y="208" fontSize="11" textAnchor="middle" fill="#69766f">{i===0?'Today':`W${i}`}</text>)}
 </svg><small>Dotted horizontal line: your minimum cash reserve.</small></div>;
}
export default function CashWorkspace() {
 const [plan,setPlan]=useState(()=>createPlan(true));const [hasEdits,setHasEdits]=useState(false);const [tab,setTab]=useState('cash');const [paste,setPaste]=useState('');const [status,setStatus]=useState('');const [saved,setSaved]=useState(false);const [previous,setPrevious]=useState(null);const importer=useRef(null);
 useEffect(()=>{try {const raw=localStorage.getItem(STORAGE);if(raw){setPlan(validatePlan(JSON.parse(raw)));setHasEdits(true);setSaved(true);}}catch {setStatus('Your saved plan could not be loaded. You can start a new plan or import a backup.');}},[]);
 useEffect(()=>{ document.title='BondSBA | Contractor Cash Flow & Bond Prep'; },[]);
 const update=(key,value)=>{setPlan(p=>({...p,[key]:value}));setHasEdits(true);setSaved(false);};
 const base=forecast(plan),stress=forecast(plan,true),complete=isCashComplete(plan);const results=plan.jobs.map(wip);const under=results.reduce((s,r)=>s+(r.under||0),0);const lossCount=results.filter(r=>r.profit<0).length;
 function start(example=false) { if((hasEdits || !plan.example) && !window.confirm('Replace the current plan? Download a backup first if you want to keep it.'))return;setPlan(createPlan(example));setHasEdits(false);setSaved(false);setStatus(example?'Example loaded. All figures are fictional.':'New plan ready. Enter your cash and weekly amounts; use 0 for weeks with no activity.');document.getElementById('workspace').scrollIntoView({behavior:'smooth'}); }
 function save() {try{validatePlan(plan);const old=localStorage.getItem(STORAGE);if(old)setPrevious(validatePlan(JSON.parse(old)));localStorage.setItem(STORAGE,JSON.stringify(plan));setSaved(true);setStatus('Saved on this browser. Download a backup to keep a portable copy.');}catch(e){setStatus(`Could not save: ${e.message}`);} }
 async function restore(e) {const file=e.target.files?.[0];if(!file)return;try{if(file.size>500000)throw new Error('Choose a backup smaller than 500 KB.');const next=validatePlan(JSON.parse(await file.text()));if((hasEdits || !plan.example)&&!window.confirm('Replace this plan with the imported backup?'))return;setPlan(next);setHasEdits(true);setSaved(false);setStatus('Backup imported. Save on this browser if you want to keep it here.');}catch(err){setStatus(`Import failed: ${err.message}`);}finally{e.target.value='';}}
 function exportBackup() {try{validatePlan(plan);download('bondsba-plan.json',JSON.stringify(plan,null,2));setStatus('Backup downloaded. It contains the figures and notes you entered.');}catch(e){setStatus(e.message);}}
 const navTab=t=>{setTab(t);document.getElementById('workspace').scrollIntoView({behavior:'smooth'});};
 return <div className="cw"><a className="cw-skip" href="#workspace">Skip to workspace</a>
 <header className="cw-header"><a href="/" className="cw-brand"><span className="cw-mark">b.</span>BondSBA<span className="cw-brand-note">BUILT FOR CONTRACTORS</span></a><nav aria-label="Main navigation"><a href="#how-it-works">How it works</a><a href="#methodology">Methodology</a><a href="/sba">SBA tools <ArrowUpRight size={13}/></a></nav><a className="cw-button dark small" href="#workspace">Open workspace <ArrowRight size={15}/></a></header>
 <main>
 <section className="cw-hero"><div><div className="cw-eyebrow"><span/> CASH FLOW + BOND PREP</div><h1>More work.<br/>Enough cash<br/><em>to carry it.</em></h1><p>See when cash gets tight, check WIP against your job-ledger totals, and prepare a clearer review for your accountant or bond agent.</p><div className="cw-actions"><button className="cw-button dark" onClick={()=>start(false)}>Build my cash plan <ArrowRight size={18}/></button><a className="cw-text-link" href="#workspace">Explore the example <ArrowDown/></a></div><div className="cw-proof"><ShieldCheck size={16}/> Free. No signup. Your figures stay in your browser.</div></div>
 <div className="cw-preview"><div className="cw-preview-top"><span>THE QUESTION BEFORE THE NEXT JOB</span><span>01 / 13 WEEKS</span></div><h2>What if payment<br/>arrives two weeks late?</h2><div className="cw-preview-values"><div><span>Expected cash low</span><strong>{money(forecast(createPlan(true)).min)}</strong></div><div><span>Stressed cash low</span><strong className="cw-negative">{money(forecast(createPlan(true),true).min)}</strong></div></div><Chart base={forecast(createPlan(true))} stress={forecast(createPlan(true),true)} opening={95000} reserve={25000}/><div className="cw-preview-note"><span className="cw-note-dot"/> Two-week payment delay + 10% higher direct costs.</div><small>Illustrative example. Change every assumption below.</small></div></section>
 <div className="cw-benefits"><span><BarChart3 size={18}/> 13-week cash forecast</span><span><FileCheck2 size={18}/> Job-by-job WIP checks</span><span><Download size={18}/> A packet you can take with you</span></div>
 <section className="cw-workspace" id="workspace"><div className="cw-section-top"><div><div className="cw-eyebrow">YOUR WORKING NUMBERS</div><h2>A little clarity. Every month.</h2></div><span className={`cw-badge ${plan.example?'example':''}`}>{plan.example?'EXAMPLE DATA':'YOUR PLAN'} · USD</span></div>
 <div className="cw-workspace-frame"><div className="cw-toolbar"><label className="cw-company">Company / project group<input aria-label="Company or project group" maxLength={200} value={plan.company} placeholder="Your company name" onChange={e=>update('company',e.target.value)}/></label><label className="cw-date">Week 1 starts<input type="date" value={plan.date} onChange={e=>update('date',e.target.value)}/></label><div className="cw-actions"><button className="cw-button light small" onClick={save}><Save size={15}/>{saved?'Saved on browser':'Save on browser'}</button><button className="cw-icon-button" title="Import a JSON plan backup" aria-label="Import a JSON plan backup" onClick={()=>importer.current.click()}><FolderOpen size={18}/></button><button className="cw-icon-button" title="Download JSON backup" aria-label="Download JSON backup" onClick={exportBackup}><Download size={18}/></button></div><input hidden ref={importer} type="file" accept=".json,application/json" onChange={restore}/></div>
 <div className="cw-tabs" role="tablist" aria-label="Workspace sections">{[['cash','01','Cash forecast'],['wip','02','WIP check'],['packet','03','Review packet']].map(([id,num,label])=><button key={id} id={`tab-${id}`} role="tab" aria-selected={tab===id} aria-controls={`panel-${id}`} tabIndex={tab===id?0:-1} onKeyDown={e=>{const tabs=['cash','wip','packet'];if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?'cash':e.key==='End'?'packet':tabs[(tabs.indexOf(id)+(e.key==='ArrowRight'?1:2))%3];setTab(next);document.getElementById('tab-'+next).focus();}}} onClick={()=>setTab(id)}><span>{num}</span>{label}</button>)}</div>
 <div className="cw-status" role="status">{status || (plan.example?'Explore this fictional contractor, or start a blank plan with your own figures.':'Changes are kept in this session until you save or download a backup.')}</div>
 {tab==='cash'&&<div id="panel-cash" role="tabpanel" aria-labelledby="tab-cash" className="cw-panel"><div className="cw-cash-grid"><div className="cw-assumptions"><h3>Start with what you know.</h3><p>Enter expected cash receipts, not invoices sent. Exclude retainage until you expect it to be released.</p><NumberField label="Cash available today ($)" value={plan.opening} onChange={v=>update('opening',v)}/><NumberField label="Minimum cash reserve ($)" value={plan.reserve} onChange={v=>update('reserve',v)}/><div className="cw-stress-box"><div className="cw-eyebrow">STRESS TEST</div><label className="cw-field"><span>Payments arrive later</span><select value={plan.delay} onChange={e=>update('delay',Number(e.target.value))}>{[0,1,2,3,4].map(n=><option key={n} value={n}>{n===0?'On time':`${n} week${n>1?'s':''} late`}</option>)}</select></label><label className="cw-field"><span>Direct costs rise <strong>{plan.overrun}%</strong></span><input aria-label="Direct cost increase percent" type="range" min="0" max="50" step="5" value={plan.overrun} onChange={e=>update('overrun',Number(e.target.value))}/></label><small>Applies to all planned receipts and direct costs. Overhead and debt payments stay unchanged.</small></div></div>
 <div><div className="cw-metrics"><div><span>Expected cash low</span><strong>{complete?money(base.min):'—'}</strong><small>Opening balance + 13 weeks</small></div><div><span>Cash needed above reserve</span><strong className={stress.gap>0?'cw-negative':''}>{complete?money(stress.gap):'—'}</strong><small>Under your stress scenario</small></div></div>{complete?<><Chart base={base} stress={stress} opening={plan.opening} reserve={plan.reserve}/><div className={`cw-insight ${stress.gap?'attention':''}`}><strong>{stress.firstBelow===null?'The scenario stays above your reserve.':stress.firstBelow===0?'Cash starts below your reserve.':`Your reserve is breached in week ${stress.firstBelow}.`}</strong><p>{stress.gap?`Review collection dates, upcoming commitments, and available funding for a ${money(stress.gap)} reserve gap.`:'Review your assumptions weekly. This scenario does not assess whether you can take on another contract.'}</p>{stress.deferred>0&&<small>{money(stress.deferred)} of planned receipts move beyond week 13; they are delayed, not lost.</small>}</div></>:<div className="cw-empty"><BarChart3 size={32}/><h3>Your forecast starts here.</h3><p>Fill in opening cash, reserve, and all 13 weeks below. Enter 0 where there is no activity.</p></div>}</div></div>
 <div className="cw-table-heading"><div><h3>The next 13 weeks</h3><p>Direct costs: labor, materials and subcontractors. Other outflows: overhead, taxes, debt and owner draws.</p></div><button className="cw-button light small" disabled={!complete} onClick={()=>download('bondsba-cash-forecast.csv',cashCsv(plan),'text/csv')}><Download size={15}/>Export CSV</button></div>
 <details className="cw-paste"><summary>Paste 13 weeks from a spreadsheet</summary><p>Copy three columns: receipts, direct costs, other outflows. Spreadsheet cells separated by tabs may include dollar signs and grouped commas, such as $20,000.00. For comma-separated rows, use plain numbers such as 20000.00. An optional first column can contain week numbers 1–13.</p><label className="cw-field"><span>Weekly rows</span><textarea rows={4} value={paste} onChange={e=>setPaste(e.target.value)} placeholder="15000&#9;27000&#9;4500"/></label><button className="cw-button light small" onClick={()=>{try{const weeks=parseWeeklyPaste(paste);update('weeks',weeks);setStatus('13 weeks imported. Review each amount below; opening cash and reserve are unchanged.');setPaste('');}catch(e){setStatus(e.message);}}}>Apply weekly rows</button></details><div className="cw-table-scroll"><table><caption className="cw-sr">Weekly cash inputs and calculated ending balances, in US dollars</caption><thead><tr><th>Week</th><th>Cash receipts ($)</th><th>Direct costs ($)</th><th>Other outflows ($)</th><th>Expected cash</th><th>Stressed cash</th></tr></thead><tbody>{plan.weeks.map((w,i)=><tr key={i}><th scope="row">{String(i+1).padStart(2,'0')}</th>{['receipts','costs','overhead'].map(key=><td key={key}><input aria-label={`Week ${i+1} ${key==='overhead'?'other outflows':key}`} type="number" min="0" max="1000000000000" step="any" inputMode="decimal" value={w[key]} placeholder="0" onChange={e=>update('weeks',plan.weeks.map((week,j)=>j===i?{...week,[key]:e.target.value}:week))}/></td>)}<td>{complete?money(base.rows[i].balance):'—'}</td><td className={complete&&stress.rows[i].balance<Number(plan.reserve)?'cw-negative':''}>{complete?money(stress.rows[i].balance):'—'}</td></tr>)}</tbody></table></div><p className="cw-fine">Include every cash outflow once. This is a weekly planning model, so a positive week-end balance can still hide a midweek shortfall. WIP figures are reviewed separately and do not automatically change this forecast.</p></div>}
 {tab==='wip'&&<div id="panel-wip" role="tabpanel" aria-labelledby="tab-wip" className="cw-panel"><WipTools plan={plan} update={update} download={download} setStatus={setStatus}/><div className="cw-table-heading"><div><h3>Is the work earning what you expected?</h3><p>Use contract values including approved changes. Estimated total cost includes costs already incurred.</p></div><button className="cw-button dark small" disabled={plan.jobs.length>=100} onClick={()=>update('jobs',[...plan.jobs,blankJob()])}><Plus size={16}/>Add job</button></div><div className="cw-job-list">{plan.jobs.map((job,i)=>{const result=results[i];return <article className="cw-job" key={i}><div className="cw-job-title"><label>Job name<input value={job.name} maxLength={200} placeholder={`Job ${i+1}`} onChange={e=>update('jobs',plan.jobs.map((j,n)=>n===i?{...j,name:e.target.value}:j))}/></label><button className="cw-icon-button" aria-label={`Remove job ${i+1}`} onClick={()=>update('jobs',plan.jobs.filter((_,n)=>n!==i))}><Trash2 size={16}/></button></div><div className="cw-job-fields">{[['contract','Contract value ($)'],['cost','Cost to date ($)'],['estimate','Estimated total cost ($)'],['billed','Billed to date ($)']].map(([key,label])=><NumberField key={key} label={label} value={job[key]} onChange={value=>update('jobs',plan.jobs.map((j,n)=>n===i?{...j,[key]:value}:j))}/>)}</div>{result.error?<p className="cw-fine">{result.error}</p>:<><div className="cw-job-results"><span><small>Complete</small><b>{(result.complete*100).toFixed(1)}%</b></span><span><small>Estimated margin</small><b className={result.margin<0?'cw-negative':''}>{(result.margin*100).toFixed(1)}%</b></span><span><small>{result.under?'Underbilled':'Overbilled'}</small><b>{money(result.under||result.over)}</b></span><span><small>Cost to complete</small><b>{money(result.remaining)}</b></span></div>{result.profit<0&&<p className="cw-warning">Estimated loss of {money(-result.profit)}. Review the cost estimate and discuss loss recognition with your accountant.</p>}{result.under>0&&<p className="cw-fine">{money(result.under)} earned but not billed. Check billing milestones and disputed changes; this is not necessarily collectible cash.</p>}{result.over>0&&<p className="cw-fine">Billings exceed earned revenue by {money(result.over)}. That amount is not extra profit and may fund work still to be completed.</p>}{result.aboveContract&&<p className="cw-warning">Billings exceed contract value. Confirm approved changes or correct the inputs.</p>}</>}</article>;})}</div>{!plan.jobs.length&&<p>Add a job to calculate its WIP position.</p>}<p className="cw-fine">Uses a simplified cost-to-cost method. It does not certify revenue recognition, bond capacity or financial statements.</p></div>}
 {tab==='packet'&&<div id="panel-packet" role="tabpanel" aria-labelledby="tab-packet" className="cw-panel"><div className="cw-table-heading"><div><h3>Give the next conversation a head start.</h3><p>A planning summary for your accountant or bond agent. Review it together.</p></div><button className="cw-button dark small" onClick={()=>window.print()}><Printer size={16}/>Print / save PDF</button></div><div className="cw-packet-grid"><div><h4>Gather the supporting documents</h4><p>Mark what you have. Your agent may request additional information.</p>{CHECKLIST.map((text,i)=><label className="cw-check" key={text}><input type="checkbox" checked={plan.checked.includes(i)} onChange={()=>update('checked',plan.checked.includes(i)?plan.checked.filter(n=>n!==i):[...plan.checked,i])}/><span>{text}</span></label>)}<label className="cw-field"><span>What changed, and what needs a decision?</span><textarea rows={5} maxLength={10000} value={plan.notes} placeholder="Example: Confirm the school payment date with the GC. Ask our accountant to review the fit-out cost estimate." onChange={e=>update('notes',e.target.value)}/></label></div><div className="cw-packet-summary"><div className="cw-eyebrow">REVIEW SUMMARY</div><h3>{plan.company||'Unnamed contractor'}</h3><p>Week 1 starts {plan.date} · {plan.example?'Example data':'User-entered figures'}</p><dl><div><dt>Expected lowest cash</dt><dd>{complete?money(base.min):'Incomplete'}</dd></div><div><dt>Stressed lowest cash</dt><dd>{complete?money(stress.min):'Incomplete'}</dd></div><div><dt>Stress reserve gap</dt><dd>{complete?money(stress.gap):'Incomplete'}</dd></div><div><dt>Underbillings (valid jobs)</dt><dd>{money(under)}</dd></div><div><dt>Jobs with estimated losses</dt><dd>{lossCount}</dd></div><div><dt>Jobs missing valid inputs</dt><dd>{results.filter(r=>r.error).length}</dd></div><div><dt>Documents marked ready</dt><dd>{plan.checked.length} / {CHECKLIST.length}</dd></div></dl><p className="cw-fine">Scenario: all receipts delayed {plan.delay} weeks; direct costs +{plan.overrun}%. No automatic credit draw. Calculations are planning estimates, not bond or loan approval.</p>{previous&&<p className="cw-fine">Previous saved plan cash low: {isCashComplete(previous)?money(forecast(previous).min):'incomplete'}. Comparison is to the plan saved before this session’s latest save.</p>}<a href="https://www.sba.gov/loans/additional-funding-opportunities/surety-bonds/surety-bond-agency-directory/" target="_blank" rel="noreferrer" className="cw-text-link">Find an SBA surety agency <ArrowUpRight size={16}/></a></div></div></div>}
 <div className="cw-workspace-bottom"><span><ShieldCheck size={15}/> Figures are calculated on this device. Saving is optional.</span><div><button onClick={()=>start(false)}>New blank plan</button><button onClick={()=>start(true)}>Load example</button><button onClick={()=>{try{localStorage.removeItem(STORAGE);setSaved(false);setStatus('Saved browser copy deleted. The current session is still open.');}catch{setStatus('Browser storage is unavailable.');}}}>Delete saved copy</button></div></div></div></section>
 <section id="how-it-works" className="cw-how"><div className="cw-eyebrow">A REPEATABLE ROUTINE</div><h2>Close the books.<br/>Open the conversation.</h2><div className="cw-steps">{[['01','Plan the cash','Update the next 13 weeks with your expected receipts and payments. Test a delay before it happens.'],['02','Check the work','Review underbillings, cost to complete, and loss-making jobs alongside your WIP schedule.'],['03','Bring the evidence','Save your plan, gather the supporting documents, and take the summary to your next review.']].map(([n,title,desc])=><div key={n}><span>{n}</span><h3>{title}</h3><p>{desc}</p></div>)}</div></section>
 <section className="cw-method" id="methodology"><div><div className="cw-eyebrow">CLEAR INPUTS. VISIBLE MATH.</div><h2>Useful numbers.<br/>No mystery score.</h2><p>BondSBA helps you prepare. Your accountant, lender and surety make their own assessments.</p></div><div><details open><summary>How does the cash stress test work?<ChevronDown size={17}/></summary><p>Each week ends with opening cash + receipts − direct costs − other outflows. The stress scenario shifts all receipts by the selected number of weeks and increases direct costs by the selected percentage. The reserve gap is the difference between your reserve and the lowest balance, including today. It is not a credit recommendation.</p></details><details><summary>How is WIP calculated?<ChevronDown size={17}/></summary><p>Percent complete = cost to date ÷ estimated total cost. Earned revenue = percent complete × contract value. Underbilling = earned revenue − billed amount, when positive. Overbilling is the reverse. Cost to complete = estimated total cost − cost to date. This simplified model does not include every accounting adjustment.</p><a href="https://www.nasbp.org/post/wip-work-in-progress-is-it-a-history-lesson-or-a-strategic-tool/" target="_blank" rel="noreferrer">Read NASBP’s WIP guidance ↗</a></details><details><summary>Where does my data go?<ChevronDown size={17}/></summary><p>This workspace does not upload your inputs. Save on browser uses local storage on this device; anyone with access to the same browser profile may see it. Backups contain your data. There is no cloud sync or account recovery. Delete the saved copy here whenever you want.</p></details><details><summary>Does this get me approved for a bond?<ChevronDown size={17}/></summary><p>No. This is a preparation tool. It does not issue bonds, estimate your bonding capacity or certify SBA eligibility. SBA’s program works through participating sureties and agencies.</p><a href="https://www.sba.gov/loans/additional-funding-opportunities/surety-bonds/" target="_blank" rel="noreferrer">Read the SBA program overview ↗</a></details></div></section>
 <section className="cw-final-cta"><h2>Make the next job<br/>a better-informed decision.</h2><button className="cw-button cream" onClick={()=>navTab('cash')}>Open my cash plan <ArrowRight size={18}/></button></section>
 </main><footer className="cw-footer"><a href="/" className="cw-brand"><span className="cw-mark">b.</span>BondSBA</a><p>Cash clarity. Better prepared.</p><div><a href="/contractor-cash-flow-forecast">Cash flow guide</a><a href="/13-week-cash-flow-template">Free input template</a><a href="/wip-schedule-errors">WIP guide</a><a href="/sba">SBA tools</a><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="mailto:contactbondsba@gmail.com">Feedback</a></div><small>Independent planning software. Not affiliated with the U.S. Small Business Administration.</small></footer>
 <div className="cw-print"><h1>BondSBA · Contractor review packet</h1><h2>{plan.company||'Unnamed contractor'}</h2><p>Week 1 starts {plan.date}. {plan.example?'FICTIONAL EXAMPLE':'USER-ENTERED FIGURES'}. USD.</p><p>Opening cash: {money(Number(plan.opening))}; minimum reserve: {money(Number(plan.reserve))}. Stress scenario: {plan.delay}-week receipt delay and {plan.overrun}% direct-cost increase.</p><p>{complete?`Expected low: ${money(base.min)}. Stressed low: ${money(stress.min)}. Reserve gap: ${money(stress.gap)}. Receipts deferred beyond week 13: ${money(stress.deferred)}.`:'INCOMPLETE CASH INPUTS: finish the cash plan before using this forecast.'}</p><table><thead><tr><th>Week</th><th>Receipts</th><th>Direct costs</th><th>Other outflows</th><th>Base cash</th><th>Stress cash</th></tr></thead><tbody>{base.rows.map((r,i)=><tr key={i}><td>{r.week}</td><td>{money(r.receipts)}</td><td>{money(r.costs)}</td><td>{money(r.overhead)}</td><td>{complete?money(r.balance):'Incomplete'}</td><td>{complete?money(stress.rows[i].balance):'Incomplete'}</td></tr>)}</tbody></table><h2>WIP review</h2><WipReconciliationSummary plan={plan}/>{plan.jobs.map((j,i)=><p key={i}><b>{j.name||`Job ${i+1}`}</b>: contract {money(Number(j.contract))}, cost to date {money(Number(j.cost))}, estimated total cost {money(Number(j.estimate))}, billed {money(Number(j.billed))}. {results[i].error||`Underbilled ${money(results[i].under)}; overbilled ${money(results[i].over)}; estimated profit ${money(results[i].profit)}; remaining cost ${money(results[i].remaining)}.`}</p>)}<h2>Supporting documents</h2>{CHECKLIST.map((text,i)=><p key={i}>{plan.checked.includes(i)?'[Ready]':'[Needed]'} {text}</p>)}<h2>Notes and next decisions</h2><p style={{whiteSpace:'pre-wrap'}}>{plan.notes||'No notes entered.'}</p><h2>Method and limits</h2><p>Cash = opening + receipts − direct costs − other outflows. Stress delays all receipts and increases direct costs; no financing is assumed. WIP uses cost-to-cost percentage complete. Estimates are not audited, and underbillings are not necessarily collectible. Weekly balances can hide intraweek cash deficits. This packet is not bond or loan approval, a complete underwriting submission, or accounting advice. Supporting documents are marked by the user, not verified by BondSBA. Prepared with bondsba.com.</p></div>
 </div>;
}
function ArrowDown(){return <span aria-hidden="true">↓</span>}
