import React, {useState} from 'react';
import {parseWipPaste,reconcileWip,wipCsv} from './model.js';
export const preciseMoney=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2}).format(n);
export function WipReconciliationSummary({plan}) {
 const c=plan.wipControls||{cost:'',billed:'',source:''};const r=reconcileWip(plan.jobs,c);
 return <div className="cw-reconciliation-summary"><h4>{r.matched?'Both entered totals match':'Check the schedule against your report'}</h4><p>Cost to date in schedule: {preciseMoney(r.totals.cost)}. Billings in schedule: {preciseMoney(r.totals.billed)}.</p><p>Cost difference: {r.costDifference===null?'Report total not entered':preciseMoney(r.costDifference)}. Billing difference: {r.billedDifference===null?'Report total not entered':preciseMoney(r.billedDifference)}.</p>{r.invalidRows>0&&<p className="cw-warning">{r.invalidRows} job(s) need valid inputs. Totals include only valid cost and billing amounts; this check cannot be marked matched.</p>}<p>Report reference: {c.source||'Not supplied'}. Differences = schedule minus report. Use the same jobs, cut-off date and job-to-date period. Matching these two totals does not verify completeness, revenue recognition or the financial statements.</p></div>;
}
export default function WipTools({plan,update,download,setStatus}) {
 const [text,setText]=useState('');const [preview,setPreview]=useState(null);const [error,setError]=useState('');const c=plan.wipControls||{cost:'',billed:'',source:''};
 const field=(key,value)=>update('wipControls',{...c,[key]:value});
 return <section className="cw-wip-tools" aria-label="WIP preparation tools">
 <div className="cw-table-heading"><div><h3>Bring your spreadsheet. Check the totals.</h3><p>Import your job list, compare it with the matching job-ledger report, and take the reviewed schedule with you.</p></div><button className="cw-button light small" disabled={!plan.jobs.length} onClick={()=>download('bondsba-wip-review.csv',wipCsv(plan),'text/csv')}>Export WIP CSV</button></div>
 <details className="cw-paste"><summary>Paste jobs from a spreadsheet</summary><p>Copy five columns in this order: job name, contract value, cost to date, estimated total cost, billed to date. Use tabs between cells. Dollar signs and grouped commas are accepted. All four amounts are required; use 0 where appropriate. Maximum 100 jobs.</p><p><a href="/templates/wip-input.tsv" download>Download the blank WIP input template</a></p><label className="cw-field"><span>Job rows</span><textarea rows={4} value={text} onChange={e=>{setText(e.target.value);setPreview(null);setError('');}} placeholder={'School project\t400000\t180000\t320000\t200000'}/></label><button className="cw-button light small" onClick={()=>{try{setPreview(parseWipPaste(text));setError('');}catch(e){setPreview(null);setError(e.message);}}}>Check pasted jobs</button>{error&&<p role="alert" className="cw-warning">{error} Your current jobs have not changed.</p>}{preview&&<div role="status"><p>{preview.length} valid job rows. Cost to date: {preciseMoney(reconcileWip(preview).totals.cost)}. Billed to date: {preciseMoney(reconcileWip(preview).totals.billed)}.</p><p>Applying replaces all current WIP jobs. Cash inputs and example labeling stay unchanged; recheck report totals afterward.</p><button className="cw-button dark small" onClick={()=>{if(!window.confirm('Replace all current WIP jobs with these checked rows? Download a backup first to keep your current jobs.'))return;update('jobs',preview);setPreview(null);setText('');setStatus('WIP jobs imported. Review the job list and compare the report totals below. Cash inputs are unchanged.');}}>Replace WIP jobs</button></div>}</details>
 <div className="cw-reconcile"><h4>Compare with your job-ledger report</h4><p>Enter independent job-to-date totals from the same reporting date and set of jobs. Do not use year-to-date totals for multi-year jobs.</p><div className="cw-control-fields">{[['cost','Report cost-to-date total ($)'],['billed','Report billed-to-date total ($)']].map(([key,label])=><label className="cw-field" key={key}><span>{label}</span><input type="number" min="0" max="1000000000000" step="0.01" value={c[key]} onChange={e=>field(key,e.target.value)}/></label>)}<label className="cw-field"><span>Report name and cut-off date</span><input value={c.source} maxLength={200} placeholder="Job ledger · August 31, 2026" onChange={e=>field('source',e.target.value)}/></label></div><WipReconciliationSummary plan={plan}/><p className="cw-fine">Your report totals and reference stay with this plan when you save or download a JSON backup. They also appear in the printed review packet.</p></div>
 </section>;
}
