export const cashGuides = [
 {
  slug:'contractor-cash-flow-forecast',title:'Contractor Cash Flow Forecast: 13-Week Guide | BondSBA',heading:'Build a contractor cash flow forecast you can update weekly',description:'Plan contractor cash receipts and payments over 13 weeks. See a worked example, test late payments, and use the free BondSBA forecast without signing up.',eyebrow:'Contractor cash planning',
  intro:'A contractor cash flow forecast answers a timing question: will the money collected be enough for the payments due? Use a 13-week view to put expected customer receipts beside labor, material, subcontractor and other cash outflows. Then test what happens when timing changes.',
  primaryCta:{href:'/#workspace',label:'Open the free cash forecast'},secondaryCta:{href:'/13-week-cash-flow-template',label:'Get the input template'},
  sections:[
   ['Start with available cash, not the bank statement alone','Use the cash you can actually spend at the start of week 1. Identify restricted balances and pending payments before selecting the opening figure. Enter a minimum cash reserve that reflects your own operating needs; the tool does not prescribe a reserve. Do not count an unapproved credit facility as available cash.'],
   ['Put receipts in the week you expect to collect them','Separate the invoice date, approval date and expected collection date. A billed job is not cash in the bank. Include retainage only when you reasonably expect it to be released and paid. If collection timing is uncertain, use the delay scenario and discuss the assumption with the person responsible for collections.'],
   ['Capture the payments that cannot disappear from the model','List labor, materials and subcontractor payments as direct costs. Include overhead, taxes, debt service, insurance and owner draws in other outflows. Reconcile the totals to the source records and count each payment once. A useful forecast is complete enough to expose a problem, not merely tidy enough to look reassuring.'],
   ['A simple worked example','Suppose opening cash is $50,000. In week 1, expected receipts are $20,000, direct costs are $30,000 and other outflows are $5,000. Ending cash is $35,000. If the receipt moves to week 2, week 1 ends at $15,000. With a $20,000 minimum reserve, the delayed case creates a $5,000 reserve gap. These are fictional planning figures, not a recommended reserve or loan amount.'],
   ['Run a stress scenario before committing more cash','BondSBA can move all planned receipts zero to four weeks later and increase direct costs by a selected percentage. Other outflows stay unchanged. Receipts pushed beyond the 13-week window are shown as deferred, not lost. The result tells you which timing assumptions need attention; it does not decide whether another contract is affordable or whether a lender will provide funding.'],
   ['Review WIP alongside the cash plan','Job progress, billing and collection measure different things. Use the WIP check to review estimated margin and billing position, then use expected collections in the cash forecast. An underbilling is not automatically an overdue receivable. Reconcile the job data with your accountant before treating it as an accounting result.'],
   ['Keep the forecast current','At each weekly review, compare the previous forecast with actual receipts and payments. Update delayed collections and cost estimates. Start the next period with actual available cash and preserve the old JSON backup if you need a record. BondSBA does not automatically roll the forecast or reconcile your accounting system.'],
   ['Understand the limits','Positive week-end cash can hide a shortfall before payroll earlier in the week. Review daily timing when the margin is narrow. The model does not calculate interest, credit availability, tax obligations or bond capacity. Keep supporting records and use the result as an input to a professional conversation.'],
  ],
  faq:[['Is this forecast free?','Yes. The browser workspace is free and does not require signup. You can save on your device or download a backup.'],['Does a profitable WIP schedule mean cash is available?','No. Revenue recognition, invoices and cash collection occur at different times. Check both job estimates and the cash receipts you actually expect.'],['Can I import a spreadsheet?','Paste 13 rows with receipts, direct costs and other outflows. The workspace accepts tab-separated spreadsheet cells with US dollar formatting, or comma-separated rows of plain numbers. It does not connect to your accounting system.']],
  sources:[['BondSBA calculation methodology','/#methodology'],['PwC Working Capital Study 25/26','https://www.pwc.co.uk/services/value-creation/insights/working-capital-study.html'],['NASBP: WIP as a strategic tool','https://www.nasbp.org/post/wip-work-in-progress-is-it-a-history-lesson-or-a-strategic-tool/']],
 },
 {
  slug:'13-week-cash-flow-template',reviewed:'September 10, 2026',title:'Free 13-Week Cash Flow Input Template for Contractors | BondSBA',heading:'Free 13-week cash flow input template for contractors',description:'Download a free CSV input template, add weekly receipts and payments, and paste it into BondSBA to calculate cash balances and payment-delay scenarios.',eyebrow:'Free template · No email required',
  intro:'Use a simple CSV input template to gather 13 weeks of expected receipts, direct costs and other outflows. Open it in your spreadsheet software, enter your figures, then paste the rows into BondSBA for the forecast and stress test. The CSV is an input worksheet; the calculations run in the workspace.',
  primaryCta:{href:'/templates/contractor-cash-flow-input.csv',label:'Download the CSV input template'},secondaryCta:{href:'/#workspace',label:'Open the forecast workspace'},
  sections:[
   ['What the template contains','There are four columns: Week, Receipts, Direct costs and Other outflows. Weeks 1 through 13 are already numbered. Amount cells are blank so you can distinguish missing data from a deliberate zero. There are no macros, scripts, account connections or hidden formulas in this CSV.'],
   ['Step 1: gather the amounts','Use receivables aging, expected payment dates, payroll commitments, supplier schedules and other known outflows. Put amounts in the week cash should move. Tab-separated cells copied from a spreadsheet can include dollar signs and grouped commas. If entering comma-separated text directly, use plain numbers without dollar signs or thousands separators. Use zero for an amount that does not apply, rather than leaving it blank.'],
   ['Step 2: check classifications','Direct costs include labor, materials and subcontractor payments for the work. Other outflows include overhead, debt payments, taxes and owner draws. Do not count a supplier payment in both columns. If costs have been included in a broader cash-payment estimate, reconcile the grouping before pasting it.'],
   ['Step 3: open a blank BondSBA plan','Select Start a blank plan. Enter actual available cash at the start of the period and your own minimum reserve. The template does not include those two figures. Giving each plan a company or project-group name makes its exported backup easier to recognize.'],
   ['Step 4: paste the weekly rows','Expand Paste 13 weeks from a spreadsheet in the cash forecast. Copy all 13 populated rows, with or without the column header, into Weekly rows. Click Apply weekly rows and review the table. Three amount columns are accepted; an optional first column must run from week 1 to week 13.'],
   ['Step 5: test a delay and export the result','Choose how many weeks later receipts arrive and whether direct costs increase. The results include the cash low and any gap to the reserve. Export CSV for the calculated balances, or use Review packet to print or save a PDF. The result CSV has more columns than the input template; use the JSON backup to reopen a complete plan.'],
   ['Example input row','For week 1, a row of 1,20000,30000,5000 means $20,000 of receipts, $30,000 of direct costs and $5,000 of other outflows. With $50,000 opening cash, expected week-end cash is $35,000. The sample is for demonstrating the format; replace every figure with your own assumptions.'],
   ['Common import problems','If a paste fails, check for exactly 13 rows, missing amount cells, extra spreadsheet total rows or incorrectly grouped amounts. Tab-separated cells accept $20,000.00. In comma-separated text, 20,000 would look like two columns: use 20000 instead. The tool rejects malformed rows rather than silently moving them into the wrong column.'],
   ['Save a copy you control','Browser saving stays on the device and browser profile you are using. Download the JSON backup for portability and keep it in a location appropriate for your business records. There is no cloud recovery. Review sensitive figures before sharing a report with an adviser.'],
  ],
  faq:[['Does the CSV calculate ending cash in Excel?','No. It is a plain input template. Paste completed rows into the BondSBA workspace to calculate cash balances, then export the results.'],['Can I use Google Sheets?','The input is a standard CSV that can be opened in spreadsheet software. Copy the completed rows as tab-separated text into the workspace.'],['Does the template predict whether I will get a bond?','No. It supports cash planning. Surety evaluation and bond approval are separate professional processes.']],
  sources:[['Forecast formulas and limitations','/#methodology'],['Step-by-step contractor cash forecast guide','/contractor-cash-flow-forecast']],
 }
];
